### ISSUE TITLE
Panicking threads cause PoisonErrors

### ISSUE THREAD

**Issue by nroi** [nroi/flexo#11]
We want flexo to be robust in the sense that if a single thread serving a single request fails, subsequent requests can still be successfully handled. This is currently not the case: If one thread runs into a `panic!`, subsequent requests will fail also:

```
flexo-server_1  | Attempt to schedule new job
flexo-server_1  | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/main.rs:89:30
flexo-server_1  | stack backtrace:
flexo-server_1  |    0:           0x4a0864 - backtrace::backtrace::libunwind::trace::h73f66b70bb6ab0fb
flexo-server_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
flexo-server_1  |    1:           0x4a0864 - backtrace::backtrace::trace_unsynchronized::h982f9756f52d4730
flexo-server_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
flexo-server_1  |    2:           0x4a0864 - std::sys_common::backtrace::_print_fmt::hcb8a98b6ac6fb3df
flexo-server_1  |                                at src/libstd/sys_common/backtrace.rs:77
flexo-server_1  |    3:           0x4a0864 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ca8145d5b4dec88
flexo-server_1  |                                at src/libstd/sys_common/backtrace.rs:59
flexo-server_1  |    4:           0x4d344c - core::fmt::write::h246c4508de237efa
flexo-server_1  |                                at src/libcore/fmt/mod.rs:1052
flexo-server_1  |    5:           0x49e427 - std::io::Write::write_fmt::h9ad42688c275e700
flexo-server_1  |                                at src/libstd/io/mod.rs:1426
flexo-server_1  |    6:           0x4a2a05 - std::sys_common::backtrace::_print::h22323acb5b25085c
flexo-server_1  |                                at src/libstd/sys_common/backtrace.rs:62
flexo-server_1  |    7:           0x4a2a05 - std::sys_common::backtrace::print::h03732590463ddb1a
flexo-server_1  |                                at src/libstd/sys_common/backtrace.rs:49
flexo-server_1  |    8:           0x4a2a05 - std::panicking::default_hook::{{closure}}::hb0df26df8d964988
flexo-server_1  |                                at src/libstd/panicking.rs:204
flexo-server_1  |    9:           0x4a26f1 - std::panicking::default_hook::ha8a56736eae7cb38
flexo-server_1  |                                at src/libstd/panicking.rs:224
flexo-server_1  |   10:           0x4a306a - std::panicking::rust_panic_with_hook::h70dad2471f7ea801
flexo-server_1  |                                at src/libstd/panicking.rs:472
flexo-server_1  |   11:           0x4a2c50 - rust_begin_unwind
flexo-server_1  |                                at src/libstd/panicking.rs:380
flexo-server_1  |   12:           0x4d1f61 - core::panicking::panic_fmt::h8c279dee2ee7cd29
flexo-server_1  |                                at src/libcore/panicking.rs:85
flexo-server_1  |   13:           0x4d1d83 - core::option::expect_none_failed::h24e1ba43092a11ab
flexo-server_1  |                                at src/libcore/option.rs:1199
flexo-server_1  |   14:           0x439953 - flexo::serve_file::he8ed5a81be4b2f79
flexo-server_1  |   15:           0x46b176 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0d28dc34c7b23eff
flexo-server_1  |   16:           0x4459bb - std::panicking::try::do_call::h32abdd41e9ebd430
flexo-server_1  |   17:           0x4a6567 - __rust_maybe_catch_panic
flexo-server_1  |                                at src/libpanic_unwind/lib.rs:86
flexo-server_1  |   18:           0x445d27 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1f5e788360a930e4
flexo-server_1  |   19:           0x4983df - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5c209cc2f51c734a
flexo-server_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
flexo-server_1  |   20:           0x4a5cf0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha982e2070915d4a3
flexo-server_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
flexo-server_1  |   21:           0x4a5cf0 - std::sys_common::thread::start_thread::hc8a38454df69b8b9
flexo-server_1  |                                at src/libstd/sys_common/thread.rs:13
flexo-server_1  |   22:           0x4a5cf0 - std::sys::unix::thread::Thread::new::thread_start::h0344e3a791d8fe52
flexo-server_1  |                                at src/libstd/sys/unix/thread.rs:80
```

where `main:89` refers to:
```rust
let result = job_context.lock().unwrap().schedule(order.clone(), get_request.resume_from);
```

**Comment by nroi** [comment]
We could also just terminate the entire application when a panic! occurs. Since flexo usually runs as a systemd service, we may just configure this service to have flexo restarted after it has crashed. This seems like a more viable strategy than having to cope with PoisonErrors, especially since flexo starts relatively fast.
