### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by desbma** [nroi/flexo#113]
**Describe the bug**
 Flexo crashes on startup, with the logs:
```
déc. 09 00:09:06 nas flexo[55290]: [2023-12-08T23:09:06.289Z INFO  flexo::mirror_flexo] Retrieved 20671 files with a total size of 44.21 GiB from local file system.
déc. 09 00:09:07 nas systemd[1]: flexo.service: Main process exited, code=dumped, status=31/SYS
```

Gdb stack trace with debug build:
```
#0  __GI___pipe (__pipedes=__pipedes@entry=0x5562b17c79d8) at ../sysdeps/unix/sysv/linux/pipe.c:29
#1  0x00007fa4434fea5a in Curl_multi_handle (hashsize=1, chashsize=3, dnssize=<optimized out>) at /usr/src/debug/curl/curl/lib/multi.c:407
#2  0x00007fa4434d8e0c in easy_perform (events=false, data=0x5562b17ca720) at /usr/src/debug/curl/curl/lib/easy.c:737
#3  curl_easy_perform (data=0x5562b17ca720) at /usr/src/debug/curl/curl/lib/easy.c:780
#4  0x00005562afa90372 in curl::easy::handler::Easy2<curl::easy::handle::EasyData>::perform<curl::easy::handle::EasyData> (self=0x7ffd5bad3fa8) at src/easy/handler.rs:2955
#5  0x00005562afa953e5 in curl::easy::handle::Easy::do_perform (self=0x7ffd5bad3fa8) at src/easy/handle.rs:1303
#6  0x00005562afa96494 in curl::easy::handle::Transfer::perform (self=0x7ffd5bad4028) at src/easy/handle.rs:1580
#7  0x00005562af9bdd9e in flexo::mirror_fetch::fetch_json::{closure#0} () at src/mirror_fetch.rs:161
#8  0x00005562af9be098 in flexo::mirror_fetch::try_num_attempts<alloc::string::String, flexo::mirror_fetch::fetch_json::{closure_env#0}, flexo::mirror_fetch::MirrorFetchError> (
    max_num_attempts=8, action=...) at src/mirror_fetch.rs:170
#9  0x00005562af9b9efe in flexo::mirror_fetch::fetch_json (json_endpoint_uri=...) at src/mirror_fetch.rs:150
#10 0x00005562af9ba026 in flexo::mirror_fetch::fetch_providers_from_json_endpoint (json_endpoint_uri=...) at src/mirror_fetch.rs:190
#11 0x00005562af9ec0d8 in flexo::fetch_auto (mirror_config=0x7ffd5bad5af8) at src/main.rs:554
#12 0x00005562af9ebb5d in flexo::rated_providers (mirror_config=0x7ffd5bad5af8) at src/main.rs:522
#13 0x00005562af9eb5f8 in flexo::initialize_job_context (properties=<error reading variable: Cannot access memory at address 0x108>) at src/main.rs:503
#14 0x00005562af9e21dc in flexo::main () at src/main.rs:77
#15 0x00005562af9c324b in core::ops::function::FnOnce::call_once<fn(), ()> () at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250
#16 0x00005562af9af69e in std::sys_common::backtrace::__rust_begin_short_backtrace<fn(), ()> (f=0x5562af9e1b10 <flexo::main>)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154
#17 0x00005562af93d591 in std::rt::lang_start::{closure#0}<()> () at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:166
#18 0x00005562afc7961b in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)>
    (self=..., args=<optimized out>) at library/core/src/ops/function.rs:284
#19 std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> (data=<optimized out>)
    at library/std/src/panicking.rs:504
#20 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> (f=...) at library/std/src/panicking.rs:468
#21 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> (f=...) at library/std/src/panic.rs:142
#22 std::rt::lang_start_internal::{closure#2} () at library/std/src/rt.rs:148
#23 std::panicking::try::do_call<std::rt::lang_start_internal::{closure_env#2}, isize> (data=<optimized out>) at library/std/src/panicking.rs:504
#24 std::panicking::try<isize, std::rt::lang_start_internal::{closure_env#2}> (f=...) at library/std/src/panicking.rs:468
#25 std::panic::catch_unwind<std::rt::lang_start_internal::{closure_env#2}, isize> (f=...) at library/std/src/panic.rs:142
#26 std::rt::lang_start_internal (main=..., argc=<optimized out>, argv=<optimized out>, sigpipe=<optimized out>) at library/std/src/rt.rs:148
#27 0x00005562af93d56a in std::rt::lang_start<()> (main=0x5562af9e1b10 <flexo::main>, argc=1, argv=0x7ffd5bad6b18, sigpipe=0)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:165
#28 0x00005562af9eface in main ()
#29 0x00007fa4431e1cd0 in __libc_start_call_main (main=main@entry=0x5562af9efab0 <main>, argc=argc@entry=1, argv=argv@entry=0x7ffd5bad6b18) at ../sysdeps/nptl/libc_start_call_main.h:58
#30 0x00007fa4431e1d8a in __libc_start_main_impl (main=0x5562af9efab0 <main>, argc=1, argv=0x7ffd5bad6b18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffd5bad6b08) at ../csu/libc-start.c:360
#31 0x00005562af8b7915 in _start ()
```

**Installation method**
The [flexo AUR package](https://aur.archlinux.org/packages/flexo) (I am the maintainer of this package).

**Distribution**
Arch Linux x86_64, up to date.

**Version**
1.6.9

**Comment by desbma** [comment]
Never mind, it was caused by my systemd hardening config.

**Comment by nroi** [comment]
Alright, thanks for maintaining the AUR package, by the way.
